import styled, { css } from 'styled-components';

/*
Interesting box shadows:

box-shadow: 4px 3px 0 #222, 6px 5px 0 #0074b7,
    -4px -3px 0 #222, -6px -5px 0 #0074b7,
    4px -3px 0 #222, 6px -5px 0 #0074b7,
    -4px 3px 0 #222, -6px 5px 0 #0074b7;

box-shadow:
    rgba(5, 169, 96, 0.4) 0px 5px,
    rgba(5, 169, 96, 0.3) 0px 10px,
    rgba(5, 169, 96, 0.2) 0px 15px;

box-shadow: 4px 3px 0 #222, 6px 5px 0 #0074b7;
*/

// Colors:
// - Yellow: #657004 / rgb(101, 112, 4)
// - Green: #04705c / rgb(5, 169, 96)
// - Blue: #036096 / rgb(0, 116, 183)

const errorShakeKeyframes = css`
/* ----------------------------------------------
 * Generated by Animista on 2022-3-27 21:10:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * But modified by me. Hehe.
 * ---------------------------------------------- */
@keyframes error-shake {
    0%,
    100% {
        -webkit-transform: translateX(0);
        transform: translateX(0);
    }

    10%,
    30%,
    50%,
    70% {
        -webkit-transform: translateX(-12px);
        transform: translateX(-12px);
    }

    20%,
    40%,
    60% {
        -webkit-transform: translateX(12px);
        transform: translateX(12px);
    }

    80% {
        -webkit-transform: translateX(6px);
        transform: translateX(6px);
    }

    90% {
        -webkit-transform: translateX(-6px);
        transform: translateX(-6px);
    }
}
`;

const zoomInKeyframes = css`
@keyframes zoom-in {
    0% {
        opacity: 0.3;
        transform: scale(0.2);
    }

    100% {
        opacity: 1;
        transform: scale(1);
    }
}
`;

export const BoardContainer = styled.div`
    margin: auto;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;

    & > .board {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        grid-template-rows: 1fr 1fr 1fr;
        grid-template-rows: 33.3% 33.3% 33.3%;
        margin-bottom: 40px;
        column-gap: 20px;
        grid-gap: 20px;
        max-width: 340px;
        animation: zoom-in 0.45s cubic-bezier(0.200, 0.480, 0.480, 0.980) both;

        & > .cell {
            border-radius: 4px;
            width: 20%;
            height: 20%;
            min-width: 100px;
            min-height: 100px;
            color: #fff;
            text-transform: uppercase;
            font-size: 3em;
            cursor: pointer;
            user-select: none;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            transition: 0.1s linear;
            position: relative;
            margin-top: -8px;
            margin-bottom: 8px;
        }

        &.disabled > .cell {
            background: #333;
            box-shadow: #2a2a2a 0px 8px;
            cursor: default;
            color: #555;
        }

        &:not(.disabled) > .cell {
            background: #036096;
            box-shadow: rgba(0, 116, 183, 0.4) 0px 8px;

            & > .index {
                font-size: 12px;
                position: absolute;
                top: 7px;
                left: 10px;
                text-shadow: none;
            }

            &.selected {
                background: #04705c;
                text-shadow: 0 4px 0 rgba(0, 0, 0, 0.2);
                box-shadow: rgba(5, 169, 96, 0.4) 0px 8px;

                &:hover {
                    background: #058e75;
                    box-shadow: rgba(5, 169, 96, 0.4) 0px 4px;
                    margin-top: -4px;
                    margin-bottom: 4px;
                }
            }

            &:not(.selected):hover {
                background: #0074b7;
                box-shadow: rgba(0, 116, 183, 0.4) 0px 4px;
                margin-top: -4px;
                margin-bottom: 4px;
            }
        }
    }

    & > .selection {
        font-size: 30px;
        color: #555;
        text-transform: uppercase;
        width: 100%;
        max-width: 340px;
        margin: 20px 20px 0;

        & > .btn {
            background: #333;
            padding: 20px;
            border-radius: 5px;
            cursor: not-allowed;
            font-weight: bold;
            box-shadow: #2a2a2a 0px 8px;
            margin-top: -8px;
            margin-bottom: 8px;
            transition: 0.1s linear;

            & > img {
                float: right;
                margin-top: -10px;
                opacity: 0.6;
            }

            &.has-selection,
            &.can-submit {
                color: #fafafa;
                cursor: pointer;
                margin-top: -8px;
                margin-bottom: 8px;
                text-shadow: 0 4px 0 rgba(0, 0, 0, 0.2);

                &:hover {
                    margin-top: -4px;
                    margin-bottom: 4px;
                }

                & > img {
                    opacity: 1;
                }
            }

            &.has-selection {
                background: #657004;
                box-shadow: rgba(101, 112, 4, 0.4) 0px 8px;

                &:hover {
                    box-shadow: rgba(101, 112, 4, 0.4) 0px 4px;
                }
            }

            &.can-submit {
                background: #820000;
                box-shadow: rgba(130, 0, 0, 0.4) 0px 8px;

                &:hover {
                    box-shadow: rgba(130, 0, 0, 0.4) 0px 4px;
                }
            }
        }
    }

    ${zoomInKeyframes}
    ${errorShakeKeyframes}
`;
